# check=skip=InvalidDefaultArgInFrom
# Copyright 2026 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Spark 4 counterpart of ./Dockerfile.
# Spark 4.2.0, Scala 2.13, Temurin JDK 25, Hadoop 3.5.0 as bundled by the
# pinned upstream image.

# Required build argument; the Makefile supplies the pinned base reference.
ARG SPARK4_BASE_IMAGE
FROM ${SPARK4_BASE_IMAGE}

USER root

# Shared with the Spark 4 CUDA image.
COPY scripts/ce-customize-spark4.sh /tmp/ce-customize-spark4.sh
COPY scripts/jars-4.2.0.txt /tmp/jars-4.2.0.txt
RUN chmod +x /tmp/ce-customize-spark4.sh && \
    /tmp/ce-customize-spark4.sh /tmp/jars-4.2.0.txt && \
    rm -f /tmp/ce-customize-spark4.sh /tmp/jars-4.2.0.txt

USER spark
