{{- if and .Values.pipelines.enabled  .Values.pipelines.ui.enabled -}}
apiVersion: v1
data:
  viewer-pod-template.json: |-
    {
      "spec": {
        "containers": [
          {
            "env": [
              {{- if eq (include "mlrun-ce.pipelines.usesStaticCredentials" . | toString) "true" }}
              {
                "name": "AWS_ACCESS_KEY_ID",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "mlpipeline-seaweedfs-artifact",
                    "key": "accesskey"
                  }
                }
              },
              {
                "name": "AWS_SECRET_ACCESS_KEY",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "mlpipeline-seaweedfs-artifact",
                    "key": "secretkey"
                  }
                }
              }
              {{- end }}
            ]
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui-configmap
{{- end -}}
