#!/bin/bash

# A script to create a remote K8s service account and a local kubeconfig to connect via an SSH tunnel.
# set -e
# set -x
# set -v

# Add common binary paths
export PATH="/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:${PATH}"

# Load .env file if present (shared with install.sh)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
fi

# Configurable settings (can be set via .env or environment)
LOCAL_TUNNEL_PORT="${LOCAL_TUNNEL_PORT:-6443}"
K8S_SA_NAME="${K8S_SA_NAME:-kubernetes}"
SUDO_PASS="${SUDO_PASS:-}"
SKIP_TLS_VERIFY="${SKIP_TLS_VERIFY:-true}"

# Update or create .env with a key=value pair
update_env_file() {
    local key="$1" value="$2"
    local env_file="${ENV_FILE}"

    if [[ -f "${env_file}" ]]; then
        if grep -q "^${key}=" "${env_file}" 2>/dev/null; then
            sed -i.bak "s|^${key}=.*|${key}=\"${value}\"|" "${env_file}" && rm -f "${env_file}.bak"
        else
            printf '\n%s="%s"\n' "${key}" "${value}" >> "${env_file}"
        fi
    else
        printf '# Auto-generated by create_kubeconfig_ce.sh\n%s="%s"\n' "${key}" "${value}" > "${env_file}"
        echo "✅ Created ${env_file}"
    fi
}

# --- Configuration ---
HISTORY_FILE="${HOME}/.kube/create_kubeconfig_history.txt"

mkdir -p "$(dirname "${HISTORY_FILE}")"
touch "${HISTORY_FILE}"

# --- Usage function ---
usage() {   
    cat <<EOF
Usage: $(basename "${0}") [OPTIONS]

Create a remote K8s service account and a local kubeconfig to connect via an SSH tunnel.

Options:
    -u, --user <username>       SSH username for the jump host
    -i, --ip <ip_address>       IP address of the jump host
    -e, --env <environment>     Cluster / environment name
    -h, --help                  Show this help message and exit

Examples:
    # Interactive mode (default)
    $(basename "${0}")

    # With flags
    $(basename "${0}") -u myuser -i 192.168.1.100 -e dev-cluster

    # With long options
    $(basename "${0}") --user myuser --ip 192.168.1.100 --env dev-cluster

    # Legacy positional arguments (backward compatible)
    $(basename "${0}") myuser 192.168.1.100 dev-cluster

If no arguments are provided, the script will run in interactive mode,
allowing you to select from previously saved configurations or enter a new one.
EOF
    exit 0
}

# --- Argument parsing ---
parse_args() {
    JUMP_HOST_USER=""
    JUMP_HOST_IP=""
    CLUSTER_ENV=""
    
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -u|--user)
                JUMP_HOST_USER="${2}"
                shift 2
            ;;
            -i|--ip)
                JUMP_HOST_IP="${2}"
                shift 2
            ;;
            -e|--env)
                CLUSTER_ENV="${2}"
                shift 2
            ;;
            -h|--help)
                usage
            ;;
            -*)
                echo "❌ ERROR: Unknown option: ${1}" >&2
                echo "Use -h or --help for usage information." >&2
                exit 1
            ;;
            *)
                # Legacy positional arguments support
                if [[ -z "${JUMP_HOST_USER}" ]]; then
                    JUMP_HOST_USER="${1}"
                    elif [[ -z "${JUMP_HOST_IP}" ]]; then
                    JUMP_HOST_IP="${1}"
                    elif [[ -z "${CLUSTER_ENV}" ]]; then
                    CLUSTER_ENV="${1}"
                else
                    echo "❌ ERROR: Too many arguments: ${1}" >&2
                    echo "Use -h or --help for usage information." >&2
                    exit 1
                fi
                shift
            ;;
        esac
    done
}

# Function to display saved configurations
display_saved_configs() {
    if [[ ! -s "${HISTORY_FILE}" ]]; then
        echo "No previously saved configurations found."
        return 1
    fi
    
    echo ""
    echo "========================================"
    echo "Previously saved configurations:"
    echo "========================================"
    
    local line_num=1
    while IFS='|' read -r user ip env; do
        echo "  [${line_num}] User: ${user}, IP: ${ip}, Env: ${env}"
        ((line_num++))
    done < "${HISTORY_FILE}"
    
    echo "  [n] Enter new configuration"
    echo "========================================"
    echo ""
    return 0
}

# Function to get user selection
get_user_choice() {
    display_saved_configs
    local has_configs=$?
    
    if [[ ${has_configs} -eq 0 ]]; then
        # Has saved configs
        local total_lines
        total_lines=$(wc -l < "${HISTORY_FILE}")
        total_lines=${total_lines// /}
        echo -n "Select an option [1-${total_lines} or 'n' for new]: "
        read -r choice
        
        if [[ "${choice}" == "n" || "${choice}" == "N" ]]; then
            return 1  # Signal to enter new config
            elif [[ "${choice}" =~ ^[0-9]+$ ]] && [[ "${choice}" -ge 1 ]] && [[ "${choice}" -le "${total_lines}" ]]; then
            # Valid selection, read that line
            local selected_line
            selected_line=$(sed -n "${choice}p" "${HISTORY_FILE}")
            JUMP_HOST_USER=$(echo "${selected_line}" | cut -d'|' -f1)
            JUMP_HOST_IP=$(echo "${selected_line}" | cut -d'|' -f2)
            CLUSTER_ENV=$(echo "${selected_line}" | cut -d'|' -f3)
            echo ""
            echo "Selected: User=${JUMP_HOST_USER}, IP=${JUMP_HOST_IP}, Env=${CLUSTER_ENV}"
            return 0  # Signal that config was selected
        else
            echo "Invalid choice. Please try again."
            get_user_choice
            return $?
        fi
    else
        # No saved configs
        return 1  # Signal to enter new config
    fi
}

# Function to prompt for new configuration
prompt_new_config() {
    echo ""
    echo "Enter new configuration:"
    echo -n "Username: "
    read -r JUMP_HOST_USER
    echo -n "IP Address: "
    read -r JUMP_HOST_IP
    echo -n "Cluster / Environment Name: "
    read -r CLUSTER_ENV
    
    # Validate inputs
    if [[ -z "${JUMP_HOST_USER}" || -z "${JUMP_HOST_IP}" || -z "${CLUSTER_ENV}" ]]; then
        echo "❌ ERROR: All fields are required!"
        exit 1
    fi
    
    # Save to config file (avoid duplicates)
    local config_line="${JUMP_HOST_USER}|${JUMP_HOST_IP}|${CLUSTER_ENV}"
    if ! grep -Fxq "${config_line}" "${HISTORY_FILE}" 2>/dev/null; then
        echo "${config_line}" >> "${HISTORY_FILE}"
        echo "✅ Configuration saved for future use."
    else
        echo "ℹ️  Configuration already exists in history."
    fi
}

# Main configuration logic
parse_args "$@"

if [[ -n "${JUMP_HOST_USER}" && -n "${JUMP_HOST_IP}" && -n "${CLUSTER_ENV}" ]]; then
    # All arguments provided via command line
    echo "Using provided arguments: User=${JUMP_HOST_USER}, IP=${JUMP_HOST_IP}, Env=${CLUSTER_ENV}"
    elif [[ -n "${JUMP_HOST_USER}" || -n "${JUMP_HOST_IP}" || -n "${CLUSTER_ENV}" ]]; then
    # Partial arguments provided - error
    echo "❌ ERROR: Partial arguments provided. All three are required:" >&2
    echo "  User: ${JUMP_HOST_USER:-<missing>}" >&2
    echo "  IP: ${JUMP_HOST_IP:-<missing>}" >&2
    echo "  Env: ${CLUSTER_ENV:-<missing>}" >&2
    echo "Use -h or --help for usage information." >&2
    exit 1
else
    # No arguments - interactive mode
    set +e
    get_user_choice
    user_choice_status=${?}
    set -e
    if [[ ${user_choice_status} -ne 0 ]]; then
        prompt_new_config
    fi
fi

REMOTE_MACHINE="${JUMP_HOST_USER}@${JUMP_HOST_IP}"

CLUSTER_NAME="${CLUSTER_ENV}"
LOCAL_CONFIG_PATH="${KUBECONFIG:-${HOME}/.kube/config_${CLUSTER_NAME}}"

# --- Main Script ---

# Exit immediately if a command exits with a non-zero status.
set -e

echo "🚀 Starting Kubernetes remote access setup..."

# Step 1: SSH to the jump host to get the API Server IP and a new token.
echo "=> Connecting to ${JUMP_HOST_IP} to discover API server and generate token..."

# The remote command now returns two values, separated by a semicolon.
REMOTE_OUTPUT=$(ssh -o "StrictHostKeyChecking=no" "${REMOTE_MACHINE}" "
    # Apply SA and CRB to ensure they exist
    kubectl apply -f - <<EOF >/dev/null 2>&1
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${K8S_SA_NAME}-admin
  namespace: kube-system
EOF
    kubectl apply -f - <<EOF >/dev/null 2>&1
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${K8S_SA_NAME}-admin-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ${K8S_SA_NAME}-admin
  namespace: kube-system
EOF

    # Create a Secret for the ServiceAccount token (works with all K8s versions)
    kubectl apply -f - <<EOF >/dev/null 2>&1
apiVersion: v1
kind: Secret
metadata:
  name: ${K8S_SA_NAME}-admin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: ${K8S_SA_NAME}-admin
type: kubernetes.io/service-account-token
EOF

    # Wait a moment for the token to be populated
    sleep 2

    # Dynamically get the API server URL
    APISERVER_URL=\$(kubectl config view --minify -o jsonpath=\"{.clusters[0].cluster.server}\")

    # Parse the URL to extract IP/hostname and port
    TEMP=\"\${APISERVER_URL#https://}\"
    # Check if URL contains a port
    if [[ \"\$TEMP\" == *\":\"* ]]; then
        REMOTE_API_SERVER_IP=\"\${TEMP%:*}\"
        REMOTE_API_PORT=\"\${TEMP##*:}\"
    else
        REMOTE_API_SERVER_IP=\"\$TEMP\"
        REMOTE_API_PORT=\"443\"  # Default HTTPS port (EKS uses 443, not 6443)
    fi

    # Get the token from the secret
    # First check if secret exists and has token
    if kubectl -n kube-system get secret ${K8S_SA_NAME}-admin-token &>/dev/null; then
        TOKEN=\$(kubectl -n kube-system get secret ${K8S_SA_NAME}-admin-token -o jsonpath=\"{.data.token}\" 2>/dev/null | base64 --decode 2>/dev/null)
    fi

    # If token is still empty, the secret might not be populated yet (K8s 1.24+)
    # Try to get it using token request API
    if [ -z \"\$TOKEN\" ]; then
        TOKEN=\$(kubectl create token ${K8S_SA_NAME}-admin -n kube-system --duration=87600h 2>/dev/null || echo \"\")
    fi

    # Output the token, discovered IP, and port, separated by semicolons
    echo \"\${TOKEN};\${REMOTE_API_SERVER_IP};\${REMOTE_API_PORT}\"
")

# Step 2: Parse the combined output from the remote host.
TOKEN=$(echo "${REMOTE_OUTPUT}" | cut -d';' -f1)
REMOTE_API_SERVER_IP=$(echo "${REMOTE_OUTPUT}" | cut -d';' -f2)
REMOTE_API_PORT=$(echo "${REMOTE_OUTPUT}" | cut -d';' -f3)

if [[ -z "${REMOTE_API_PORT}" ]]; then
    REMOTE_API_PORT="6443"
fi

# Debug output
echo "=> Debug: Remote output length: ${#REMOTE_OUTPUT}"
echo "=> Debug: Token length: ${#TOKEN}"
echo "=> Debug: API Server: ${REMOTE_API_SERVER_IP}:${REMOTE_API_PORT}"

# Error handling
if [[ -z "${TOKEN}" ]] || [[ -z "${REMOTE_API_SERVER_IP}" ]]; then
    echo "❌ ERROR: Failed to retrieve token or API Server IP from the remote server."
    echo "Raw remote output: ${REMOTE_OUTPUT}"
    exit 1
fi

echo "✅ Token and API Server (${REMOTE_API_SERVER_IP}:${REMOTE_API_PORT}) successfully retrieved."

# Step 3: Create the local kubeconfig file.
echo "=> Creating local kubeconfig at ${LOCAL_CONFIG_PATH}..."
mkdir -p "$(dirname "${LOCAL_CONFIG_PATH}")"
cat <<EOF > "${LOCAL_CONFIG_PATH}"
apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: ${CLUSTER_NAME}
  cluster:
    server: https://127.0.0.1:${LOCAL_TUNNEL_PORT}
    insecure-skip-tls-verify: ${SKIP_TLS_VERIFY}
users:
- name: ${K8S_SA_NAME}-admin
  user:
    token: ${TOKEN}
contexts:
- name: ${K8S_SA_NAME}-admin@${CLUSTER_NAME}
  context:
    cluster: ${CLUSTER_NAME}
    user: ${K8S_SA_NAME}-admin
current-context: ${K8S_SA_NAME}-admin@${CLUSTER_NAME}
EOF
echo "✅ Kubeconfig file created."

# Save KUBECONFIG path to .env so install.sh picks it up automatically
update_env_file "KUBECONFIG" "${LOCAL_CONFIG_PATH}"
echo "✅ KUBECONFIG saved to ${ENV_FILE}"

# Step 4: Start the SSH tunnel in the background using the discovered IP and port.
echo "=> Starting SSH tunnel to ${REMOTE_API_SERVER_IP}:${REMOTE_API_PORT} in the background..."

echo "=> Cleaning up any existing tunnels on port ${LOCAL_TUNNEL_PORT}..."
pkill -f "ssh.*${LOCAL_TUNNEL_PORT}:.*" || true
lsof -ti:"${LOCAL_TUNNEL_PORT}" | xargs kill -9 2>/dev/null || true
sleep 1

# Start the new tunnel (local port -> remote API server port)
echo "=> Establishing new tunnel: ${LOCAL_TUNNEL_PORT} -> ${REMOTE_API_SERVER_IP}:${REMOTE_API_PORT} via ${REMOTE_MACHINE}..."
if [[ -n "${SUDO_PASS:-}" ]]; then
    sshpass -p "${SUDO_PASS}" ssh -f -N -L "${LOCAL_TUNNEL_PORT}":"${REMOTE_API_SERVER_IP}":"${REMOTE_API_PORT}" "${REMOTE_MACHINE}"
else
    ssh -f -N -L "${LOCAL_TUNNEL_PORT}":"${REMOTE_API_SERVER_IP}":"${REMOTE_API_PORT}" "${REMOTE_MACHINE}"
fi
sleep 2

# Check if the tunnel process is running
if ! pgrep -qf "${LOCAL_TUNNEL_PORT}:${REMOTE_API_SERVER_IP}:${REMOTE_API_PORT}"; then
    echo "❌ ERROR: The SSH tunnel process could not be found. Check your SSH connection."
    exit 1
fi
echo "✅ Tunnel process confirmed to be running for ${REMOTE_API_SERVER_IP}:${REMOTE_API_PORT}."

# --- Final Instructions ---
printf "\n🎉 Setup Complete!\n"
printf "Your kubeconfig is ready at:\t%s\n\n" "${LOCAL_CONFIG_PATH}"
printf "To use this kubeconfig:\n"
printf "  export KUBECONFIG=\"%s\"\n" "${LOCAL_CONFIG_PATH}"
printf "  kubectl get nodes\n\n"
printf "Or pass it explicitly:\n"
printf "  kubectl --kubeconfig=\"%s\" get nodes\n\n" "${LOCAL_CONFIG_PATH}"
printf "Testing connection now:\n\n"

kubectl get nodes --kubeconfig="${LOCAL_CONFIG_PATH}"